const list = [
    {
      id: 1,
      title: "Natural Special Falooda",
      author: "by Wonder House Books | 25 April 2018",
      price: 140,
      img: "https://res.cloudinary.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/ae3qqfev6j7hzhxw6if3",
      amount: 1,
    },
    {
      id: 2,
      title: "BlueBerry Magic JOE",
      author: "by Maple Press  | 1 September 2020",
      price: 98,
      img: "https://www.allrecipes.com/thmb/B1z_tl24FfEDtheuIgp-J9YUBV8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/435381-ice-cream-base-Pam-Ziegler-Lutz-4x3-1-88949560ccf04d0fae12225be5b83fc2.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "MixFruit Magic'S  JoE",
      author: "by Om Books Editorial Team  | 25 November 2018",
      price: 143,
      img: "https://static.toiimg.com/photo/84917454.cms",
      amount: 1,
    },
    {
      id: 4,
      title: "Mango Slice Magic Ice Cream",
      author: "by Wonder House Books | 25 April 2018",
      price: 57,
      img: "https://www.funfoodfrolic.com/wp-content/uploads/2020/04/Mango-Ice-Cream-Thumbnail.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Cholocate StraWBerry Crack MIX",
      author: "by Wonder House Books  | 1 January 2018",
      price: 149,
      img: "https://www.carveyourcraving.com/wp-content/uploads/2021/06/chocolate-icecream-in-an-icecream-maker.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "DasherCranK Choco Special",
      author: "by Om Books Editorial Team | 30 September 2020",
      price: 55,
      img: "https://amyshealthybaking.com/wp-content/uploads/2016/07/25-minute-chocolate-ice-cream_a-LL.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Pistachio DasherCranK Special",
      author: "by Om Books Editorial Team  | 1 January 2021",
      price: 69,
      img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/04/pistachio-ice-cream-recipe.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "HONEY CRANK TOTOBA",
      author: "by Wonder House Books  | 6 December 2020",
      price: 99,
      img: "https://culinaryshades.com/wp-content/uploads/2021/09/Salted-Caramel-IC-sqr.jpg",
    },
    {
      id: 9,
      title: "Fruit Magic ICE CREAM ",
      author: "by Content Team at Target Publications",
      price: 80,
      img: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/super-easy-fruit-ice-cream-b288af9.jpg?quality=90&webp=true&resize=440,400",
      amount: 1,
    },
    {
      id: 10,
      title: "THREE-STAR CUPMagiC",
      author: "by Maple Press | 1 September 2021",
      price: 386,
      img: "https://www.keep-calm-and-eat-ice-cream.com/wp-content/uploads/2022/08/Ice-cream-sundae-hero-11.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Oreo-KiNG DasherCranK",
      author: "by Rebecca Smith  | 14 December 2021",
      price: 120,
      img: "https://homebodyeats.com/wp-content/uploads/2022/08/ice-cream-oreo-cookie-500x500.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "DasherCranK Ube Ice Cream",
      author: "by Sudha Murty | 1 January 2015",
      price: 157,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwFls_JVPVXgZpjbikRMXNZr-BbMaq1_bM2VF3Nl3Qcbex6BRNnKLxbOO2X_oI4TSZQG8&usqp=CAU",
      amount: 1,
    },
  ];
  
  export default list;